name: Update cross-build metadata file

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
        required: true

jobs:
  update_cross_build_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install pyodide-build
        run: |
          python -m pip install --upgrade pip
          pip install ./pyodide-build

      - name: Get version number (release)
        if: github.event_name == 'release'
        run: |
          echo "VERSION=${{ github.event.release.name }}" > $GITHUB_ENV

      - name: Get version number (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" > $GITHUB_ENV

      - name: Update cross-build metadata file
        working-directory: tools
        run: |
          python update_cross_build_releases.py "${{ env.VERSION }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update cross-build metadata file for version ${{ env.VERSION }}
          title: Update cross-build metadata file for version ${{ env.VERSION }}
          body: |
            This PR updates the cross-build metadata file.
          branch: update-cross-build-metadata-${{ env.VERSION }}
          base: main
          branch-suffix: timestamp
          draft: true
          add-paths: |
            pyodide-cross-build-environments.json
