name: Update cross-build metadata file

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version number to update to. This should not contain the 'v' prefix, since our releases on GitHub do not have it."
        required: true

env:
  version: ${{ github.event_name == 'release' && github.event.release.tag_name || github.event.inputs.version }}

jobs:
  update_cross_build_releases:
    runs-on: ubuntu-latest
    steps:
      # Note: we check out the main branch so that the cross-build metadata
      # file is always updated on top of the latest state of the repository.
      - name: Checkout main branch
        uses: actions/checkout@v6
        with:
          submodules: recursive
          ref: main

      - uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Install pyodide-build
        run: |
          python -m pip install --upgrade pip
          make pyodide_build

      - name: Update cross-build metadata file
        id: update_cross_build_metadata
        working-directory: tools
        run: |
          python update_cross_build_releases.py "${{ env.version }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update cross-build metadata file for version ${{ env.version }} [skip ci]
          title: Update cross-build metadata file for version ${{ env.version }}
          body: |
            This PR updates the cross-build metadata file for the new version ${{ env.version }}.
            Requesting a review from the @pyodide/core team.
          branch: update-cross-build-metadata-${{ env.version }}
          base: main
          branch-suffix: timestamp

      - name: Create an issue if the update fails
        if: failure() || steps.update_cross_build_metadata.outcome == 'failure'
        uses: dacbd/create-issue-action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Update cross-build metadata file for version ${{ env.VERSION }} failed
          body: |
            ## Description

            The update of the cross-build metadata file for version ${{ env.VERSION }} failed.

            ## Additional information

            Please check the logs at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            for more information and update the metadata file manually if necessary.

          labels:
          assignees: ${{ github.actor }}
